/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(distance_access_code_tag_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(50203d87c2a51d2602ba268de9beab26)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/distance/distance_access_code_tag_ff.h>
// pydoc.h is automatically generated in the build directory
#include <distance_access_code_tag_ff_pydoc.h>

void bind_distance_access_code_tag_ff(py::module& m)
{

    using distance_access_code_tag_ff    = gr::distance::distance_access_code_tag_ff;


    py::class_<distance_access_code_tag_ff, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<distance_access_code_tag_ff>>(m, "distance_access_code_tag_ff", D(distance_access_code_tag_ff))

        .def(py::init(&distance_access_code_tag_ff::make),
           D(distance_access_code_tag_ff,make)
        )
        



        ;




}








